#!/usr/bin/env bash

CHANGED_FILES=$(git diff HEAD --name-only)
echo "${CHANGED_FILES}"

if [ -n "${CHANGED_FILES}" ]; then
  ./vendor/bin/php-cs-fixer fix -vvv --config=.php-cs-fixer.php --show-progress=dots --using-cache=no $(printf -- '--path-mode=intersection -- %s' "${CHANGED_FILES}")
else
  echo "Не найдено измененных файлов."
fi
